### ISSUE TITLE
Migrations don't work on Windows

### ISSUE THREAD

**Issue by mordechaim** [romeerez/orchid-orm#263] opened 2024-05-09 21:44 UTC
I'm trying to use the new migration strategy introduced in 1.25 but it fails loading the `./db` file:

```ts
import { rakeDb } from 'orchid-orm/migrations'
import { BaseTable } from './baseTable'

export const change = rakeDb(
    { databaseURL: process.env.DIRECT_URL },
    {
        baseTable: BaseTable,
        snakeCase: true,
        migrationsTable: 'migrations',
        migrationsPath: './migrations',
        dbPath: './db',
        commands: {
            async seed() {
                const { seed } = await import('./seed')
                await seed()
            }
        }
    }
)
```

Running `npm run db g` crashes with:

```shell
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
    at new NodeError (node:internal/errors:405:5)
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/load:138:11)
    at defaultLoad (node:internal/modules/esm/load:89:3)
    at nextLoad (node:internal/modules/esm/hooks:733:28)
    at Z (file:///C:/Users/<redacted>/node_modules/tsx/dist/esm/index.mjs:2:1750)
    at nextLoad (node:internal/modules/esm/hooks:733:28)
    at Hooks.load (node:internal/modules/esm/hooks:377:26)
    at MessagePort.handleMessage (node:internal/modules/esm/worker:168:24)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:778:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}

Node.js v20.5.0
```

`db` script is defined as `tsx src/db/dbScript.ts`

**Comment by romeerez** [comment] 2024-05-11 05:58
WIll fix it for you, just want to share that Windows is so tough. It layed down broken after update for about a year on my machine, but luckly, I reinstalled it recently. So far I figured out how to enable developers mode, installed node.js. Now trying to install postgres and I'm a bit stuck with it.

Fireship yesterday posted a video about Windows vs Macos vs Linux for devs, how much of a lier he is. Windows devs should realize and be proud of how much difficulties they have to overcome for what they're doing compared to Mac and Linux users. Even disabling automatic update is such a challenge, so every time Windows is shutting down and updates things I'm praying that I won't need to reinstall it again.

How to install postgres in my linux:
```shell
yay -S postgresql
```
Ready.

How to install postgres on windows: lol, I googled it, opened official [postgres installers page](https://www.postgresql.org/download/windows/), they have a link [postgres installer](https://www.enterprisedb.com/downloads/postgres-postgresql-downloads), which has a link back to [postgres downloads](https://www.postgresql.org/download/), clicking on Windows and I'm redirected back to the first page :)

Maybe it's easier when using WSL, but last time I tried to install WSL it was also a journey on itself, so much patience and dedication is needed. All those folks who claims things like "windows is for noobs" are so far form reality, developers on Windows are true heros who can fight back complexities that would make Mac/Linux users to give up and run away.

**Comment by romeerez** [comment] 2024-05-11 08:51
Fixed! Update `orchid-orm`, now it should be fine.

**Comment by mordechaim** [comment] 2024-05-12 02:41
Amazing @romeerez you rock!

**Comment by mordechaim** [comment] 2024-05-12 19:27
I'm not sure what I'm doing wrong. I'm now trying the latest version; importing the file now works but it fails to load the `db` object which is correctly exported as `db` named export.

```ts
import { orchidORM } from 'orchid-orm'
import { UserTable } from './tables/user.table'

export const db = orchidORM(
    { databaseURL: process.env.DATABASE_URL },
    {
        user: UserTable
    }
)
```

I get the following error:
```
Error: Unable to import OrchidORM instance as db from ./db
    at getDbFromConfig (C:\Users\<redacted>\node_modules\orchid-orm\src\migrations\generate\generate.ts:192:11)
    at generate (C:\Users\<redacted>\node_modules\orchid-orm\src\migrations\generate\generate.ts:82:14)
    at runCommand (C:\Users\<redacted>\node_modules\rake-db\src\rakeDb.ts:152:11)
```


In fact, I ran the exact same code from generate.ts:192:11 myself and it properly loaded the module. I have no clue why your code fails to load it.

**Comment by mordechaim** [comment] 2024-05-12 19:34
Adding a print statement in your code in my `node_modules` shows that `module` is `[Module: null prototype] { default: { db: [Getter] } }` instead of `{ db: [Getter] }` from my version of the import.

**Comment by mordechaim** [comment] 2024-05-12 19:41
FWIW, I do see in your code that you `require` the module if `import` fails. `require`ing in my code fails if I use a file URL (the fix for Windows).

In fact, even if I do `import` without resolving to a file URL it works on windows. So I have no clue why we had this Widnows issue in first place.

**Comment by mordechaim** [comment] 2024-05-12 19:54
Now, this is becoming more intense... I manually added `.default` in the node_modules version of the code so I can run the migration.

It now fails with the following error: 

```
Error: Failed to verify generated migration: some of database changes were not applied properly. This is a bug, please open an issue, attach the following migration code:

change(async (db) => {
  await db.createTable('user', (t) => ({
    id: t.identity().primaryKey(),
    created: t.timestamps().createdAt,
    updated: t.timestamps().updatedAt,
    name: t.text(0, 1000),
  }));

  await db.dropTable(
    'migrations',
    {
      noPrimaryKey: true,
    },
    (t) => ({
      version: t.text(),
      name: t.text(),
    }),
  );
});

    at generate (C:\Users\<redacted>\node_modules\orchid-orm\src\migrations\generate\generate.ts:129:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runCommand (C:\Users\<redacted>\node_modules\rake-db\src\rakeDb.ts:152:11)

Node.js v20.5.0
```

**Comment by mordechaim** [comment] 2024-05-12 19:57
It doesn't end here, I see that the interactive CLI asked me if I want to rename the table from the existing `migrations` table. Now, this is my custom name for the `schemaMigrations` table (since I like concise names). It attempts to delete this table although it is defined as the migrations table name in the rakedb config.

Removing the override and trying to generate with the default migration table name still errors, but differently:

```
C:\Users\<redacted>\node_modules\orchid-orm\src\migrations\generate\generate.ts:129
      throw new Error(
            ^


Error: Failed to verify generated migration: some of database changes were not applied properly. This is a bug, please open an issue, attach the following migration code:

change(async (db) => {
  await db.createTable('user', (t) => ({
    id: t.identity().primaryKey(),
    created: t.timestamps().createdAt,
    updated: t.timestamps().updatedAt,
    name: t.text(0, 1000),
  }));
});

    at generate (C:\Users\<redacted>\node_modules\orchid-orm\src\migrations\generate\generate.ts:129:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runCommand (C:\Users\<redacted>\node_modules\rake-db\src\rakeDb.ts:152:11)

Node.js v20.5.0
```

**Comment by romeerez** [comment] 2024-05-12 20:59
It's expected for a large new feature to have some issues initially, so it will take some time to polish.

Regarding the importing problem, please make a min reproduction repo, because it worked for me on Windows when I was fixing it. I used `tsx` as a code runner, perhaps you were using something different? `import`s are implemented differently by every tool to run TS code.

The second problem with "migrations" is apparently a bug that's will be quick to fix, by simply unhardcoding the migrations table name.

**Comment by mordechaim** [comment] 2024-05-12 21:01
Thanks.

I'll create a reproduction soon. Even after working around the import issue we still had this crash not related to the hard coded migration table name (in the last comment of mine)

**Comment by mordechaim** [comment] 2024-05-12 21:22
I'm not at my computer at the moment, but I suspect I need to change the `module` and `moduleResolution` keys in tsconfig.json.

Currently `module` is defined as `esnext` and `moduleResolution` as `node`.

It could be the windows issue isn't at all related to Windows, but instead with this configuration.

**Comment by mordechaim** [comment] 2024-05-12 21:40
Nope, tweaking those setting didn't seem to make any difference, but the reason I initially changed those settings around was because another issue I had when setting `moduleResolution` to `node`. It should probably be opened under a separate issue.

![image](https://github.com/romeerez/orchid-orm/assets/12547785/71acce1f-00ac-470d-9a7d-cc4866c8b0f0)

**Comment by mordechaim** [comment] 2024-05-12 21:57
Going back to the original issue of Windows, I believe the solution should not be to resolve to a file URL, but instead not resolve as an absolute file.

both `import` and `require` handle importing a file from the local filesystem perfectly, but it seems that `path.resolve(config.basePath...)` resolves the file to the filesystem root (C:) instead of against the CWD which causes the resolution to fail.

To me, this boils down to a bug in resolving against `config.basePath` instead.

**Comment by mordechaim** [comment] 2024-05-12 22:46
Ok ok! So after creating a brand new project for the purpose of the reproduction it turns out that I removed this part from the rakeDb config which caused the import problems resolving to the default export:

```
import: (path) => import(path),
```
This doesn't solve the windows import issue though. Installing 1.26.1 will still not work on Windows.

--------

The issue with the generation was due to something else entirely, namely, I created a `defaults()` column type in the base table and use it in the table definition as `...defaults()`. This somehow triggered an error. Importing the fields verbatim instead of spreading did properly create the migration.

But! back to a previous issue I created a while back, it won't generate the column names correctly for timestamps.

This is my table definition

```ts
import { BaseTable } from '../baseTable'

export class UserTable extends BaseTable {
    readonly table = 'user'
    columns = this.setColumns(t => ({
        id: t.identity().primaryKey(),
        created: t.timestamps().createdAt.asDate(),
        updated: t.timestamps().updatedAt.asDate(),
        name: t.text(0, 1000)
    }))
}
```

Which generates the following:

```ts
import { change } from '../dbScript';

change(async (db) => {
  await db.createTable('user', (t) => ({
    id: t.identity().primaryKey(),
    created: t.name('created_at').timestamps().createdAt,
    updated: t.name('updated_at').timestamps().updatedAt,
    name: t.text(0, 1000),
  }));
});
```

And creates the wrong column names in the database.

-----------

So to wrap up: 
- Omitting the `import` key from the rakeDb config should default to the standard import directive.
- I believe the Windows bug was fixed in the wrong way, we need to deal with resolving against the basePath instead of coercing to a file URL.
- The generation process ignores the migration table name override
- Importing `orchid-orm/migrations`  shows an error when module resolution isn't set to bundler etc.
- Generation fails when spreading my custom defaults column type (but works well with the built in `timestamps()`)
- Renaming the timestamps is ignored in the migration file

**Comment by IlyaSemenov** [comment] 2024-05-13 03:23
> Importing `orchid-orm/migrations` shows an error when module resolution isn't set to bundler etc.

This is how it's supposed to work. What else would you pick for moduleResolion anyway? `node10`? If that's a must for whatever legacy reason, you can fall back to using the separately published `rake-db` instead of `orchid-orm/migrations`. But for most projects `Bundler` is the best pick.

**Comment by mordechaim** [comment] 2024-05-13 03:48
Yeah you could be right, I just wasn't sure why I was seeing this error so wanted to bring to the attention of the maintainers.

**Comment by romeerez** [comment] 2024-05-13 10:02
Hey @mordechaim, I published a few fixes, testing this on Windows and it seems to be working fine on my side.

- import: I've changed it to be required in the config, but I didn't fix it because isn't broken for me, so if you still have import errors please create a min repro
- custom "migrations" table name: un-hardcoded, it should be fine now
- "Failed to verify generated migration": don't know how to reproduce, it may be related to custom migrations table name and then it's fixed, or it may be related to customly named timestamps, then please show how to you define the timestamps, because I tried to use "created" and "updated" timestamps and it worked for me.
  ```ts
  class Table extends BaseTable {
    columns = this.setColumns(t => ({
      created: t.timestamps().createdAt,
      updated: t.timestamps().updatedAt,
    }))
  }
  ```
- `node` module resolution doesn't work: fortunately, TS error message is descriptive here, so not a problem unless you really need that option.
- Relative imports are trickier than absolute because files are imported by the library from deep inside of `node_modules`, that's why they are resolved into absolute paths.
-
  > Generation fails when spreading my custom defaults column type (but works well with the built in timestamps())
  
  Let me see your `defaults`, cannot fix it otherwise.
-
  > Renaming the timestamps is ignored in the migration file
  How do you rename it?

One issue that remains is that the init script creates a package.json with "NODE_ENV=development" in the `db` script, but envs doesn't work on Windows in such a way. Probably, I should change it to cross-env, or just to remove it if it itsn't really needed.

**Comment by mordechaim** [comment] 2024-05-13 12:24
Thanks @romeerez. I'll create a reproduction later.

Regarding absolute paths, of course we can't rely on relative paths entirely. My point was to resolve absolute against the CWD root, not the file system root. The entire windows issue is only happening because the ESM loader sees the "C:" part of a Windows absolute file.

(I'm now thinking, since we require the `import` key in the config, we can now rely on relative paths, since import looks at the defining file, no?)

Btw, why do we even need this entire loading mechanism if first place? We can't we just pass in an instance of `db` and call it a day?

>> Renaming the timestamps is ignored in the migration file
>
> How do you rename it?

You can see in the code snippet in [this comment](https://github.com/romeerez/orchid-orm/issues/263#issuecomment-2106398533)

Regarding setting `NODE_ENV`, yeah removed it as I'm using Next.js which automatically sets the environment according to the selected start script. In any case, I never rely on the compiled version anyway and just run "production" migrations with tsx, so I don't need this env at all. Since we removed app code generation this doesn't even affect anything I think.

**Comment by romeerez** [comment] 2024-05-13 12:56
> (I'm now thinking, since we require the import key in the config, we can now rely on relative paths, since import looks at the defining file, no?)

Yes, if there will be a good reason to switch from absolute to relative, the import is defined in the "dbScript" file and it could serve as a root point for relative paths. But I hope that absolute paths will work well and no need to rework and retest it on various TS runners and platforms.

> Btw, why do we even need this entire loading mechanism if first place? We can't we just pass in an instance of db and call it a day?

That's right it would be much simpler, but the `db` file links together all project tables, it can be a large tree of project files, it is only needed when generating migrations and won't be loaded otherwise. It could be that migrations are bundled to be executed on a remote server, and having a directly imported `db` would increase bundle size significantly.

> You can see in the code snippet in https://github.com/romeerez/orchid-orm/issues/263#issuecomment-2106398533

I see, probably related to `asDate`, will check this.

**Comment by mordechaim** [comment] 2024-05-13 19:39
On a clean project, everything now seems to work perfectly!

On my existing project I'm still having slight issues with timestamps, I'll investigate further,

**Comment by mordechaim** [comment] 2024-05-13 19:46
Ah! Using `snakeCase: true` in the rakeDb config causes the timestamp issues. In my clean project I initially didn't set it to true.

If the table defines anything that uses `timestamps()` it crashes with an error, and in some cases it will force the `name('created_at')` option even though it's not set in the table definition.

**Comment by romeerez** [comment] 2024-05-14 16:53
Trying to resolve the custom timestamp name related issue, it appears to be a tough one so it will take some time.

**Comment by romeerez** [comment] 2024-05-14 17:14
I published a fix, and now that should work fine.

Custom timestamps names in snake case mode

```ts
created: t.timestamps().createdAt,
updated: t.timestamps().updatedAt,
```

will be named `created` and `updated` in the database, as expected.

**Comment by mordechaim** [comment] 2024-05-14 17:18
Yes! I confirm it works as expected. Thanks @romeerez

**Comment by romeerez** [comment] 2024-05-14 17:28
Awesome! Any more troubles with this for now, or let's close?

**Comment by mordechaim** [comment] 2024-05-14 17:40
I believe all issues have been hashed out by now, though I haven't thoroughly tested every scenario.

The only thing I would probably do differently is to resolve the db file against the CWD root instead of filesystem root, and in turn not need to get file URLs for Windows.

**Comment by romeerez** [comment] 2024-05-14 17:54
Imports are relative to a file where they're called (`dbScript.ts`). Reworking and retesting how it works on various platforms isn't fun, so I'm happy with it as long as it works.

**Closed by romeerez** 2024-05-14 17:54 UTC
Labels: bug

**Comment by mordechaim** [comment] 2024-05-14 17:58
> Imports are relative to a file where they're called (`dbScript.ts`). Reworking and retesting how it works on various platforms isn't fun, so I'm happy with it as long as it works.

Yeah! Agree with this sentiment. Thanks again!
