### ISSUE TITLE
Random conflicts creating schemaMigrations table when migrating empty database

### ISSUE THREAD

**Issue by krichards** [romeerez/orchid-orm#211] opened 2023-10-25 09:54 UTC
Occasionally we see random build failures with the rakedb migration where the schemaMigration table seems to be attempted to attempt to be created multiple times, and then we get a failure because it already exists.

it **could** be a problem in our code, but thought I'd ask if this is something someone else has encountered?

**Comment by romeerez** [comment] 2023-11-07 05:52
Sorry, I didn't respond earlier. Could you give more context? What command is failing? You're saying there could be a problem in your code, could you share it?

**Comment by krichards** [comment] 2023-11-15 11:24
The other thing to add is that the logs show 2 entries **Created versions table**

`
Created versions table
(7.3ms) CREATE TABLE "hid" (
  "hid" varchar(255) PRIMARY KEY,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp with time zone NOT NULL DEFAULT now()
)
(5.0ms) CREATE UNIQUE INDEX "hid_hid_idx" ON "hid" ("hid")
Migrated file:///home/kevin/projects/haven/haven-identity/adapter/hid/orchid-pgsql/dist/db/migrations/ts/20230328123026_createHid.ts
(11.4ms) CREATE TABLE "hid_to_email" (
  "email" text PRIMARY KEY,
  "hid" text NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp with time zone NOT NULL DEFAULT now()
)
(8.9ms) CREATE UNIQUE INDEX "hid_to_email_email_idx" ON "hid_to_email" ("email")
Created versions table
/home/kevin/projects/haven/haven-identity/node_modules/.pnpm/pg@8.11.3/node_modules/pg/lib/client.js:526
          Error.captureStackTrace(err);
                ^

error: duplicate key value violates unique constraint "pg_type_typname_nsp_index"

`

**Comment by romeerez** [comment] 2023-11-15 13:19
Could you share your config/script that is launching migrations? I mean the one with `rakeDb`. And what is the command to launch?
Is it possible that the migrations are running in parallel by CI? You said you can reproduce this locally, so I guess it's not related to running in parallel.

**Comment by krichards** [comment] 2023-11-16 15:37
Not easily I'd have to try and distill it down to the basics.

**Comment by krichards** [comment] 2023-11-16 16:48
[cutdown.tar.gz](https://github.com/romeerez/orchid-orm/files/13380251/cutdown.tar.gz)

this is a cutdown version, not really doing anything odd about how we use rake apart from modifying the schema import  to work with node rather than node-ts.

**Comment by romeerez** [comment] 2023-11-18 12:53
Earlier this week I pushed updates for the initializer script ([Quickstart](https://orchid-orm.netlify.app/guide/quickstart.html)), and it makes a difference.

Up until recently, it was `ts-node` by default, and no building of migrations, and no running `rake-db` over compiled files.

Now it offers to choose between `tsx`, `vite-node`, and `ts-node`. Also will use `bun` if you run it with `bun`.
For `tsx` and `vite-node` it generates special configs for migrations, and it adds a script to `package.json` to build migrations, and a script to run compiled migrations.

I see that in your case you're compiling the migrations and then you run `dist/main.js` to run migrations. You copy `ts` migration files into `dist` so `rake-db` is still running over the original `ts` files. It works on my computer: I dropped db and test db, compiled, executed `pnpm migrate`, repeated several times, and it works for me, it creates two tables, creates unique indexes, for both `DATABASE_URL` and `DATABASE_TEST_URL`. So I'm still not sure what is the issue.

Why compile migrations before running? It makes sense if you compile in CI, deploy files to a server, and migrations are running on a server, in this way the command to migrate takes noticeably less time to execute. In such case, I suggest trying the init script above choosing `tsx`, then to copy and adapt configs and scripts to your project. But it may not help because you probably have a project with commonjs output, and those scripts are configured for esm (require "type": "module" in package.json), and I should add an option to choose commonjs to the init script and change configs for it.

A simple solution would be to skip the compiling step and run migrations over `.ts` files, and I can suggest `tsx` for running it as it works well for me.

**Comment by krichards** [comment] 2023-11-24 14:50
Yeah - the migrations are compiled because they are run in an init container in kubernetes as part of migration.

What version of postres are you using?  (just wondering).

When you ran the experiment did you start from an empty database each time.  You need to start with no schemaMigration table in order to test it reliably.

My guess was that it was finding the schema migration missing for each migration, before running each script, and there was race condition which meant the schemaMigration table was tried to be created twice  But could not see how that would be the case.

**Comment by romeerez** [comment] 2023-11-25 17:48
My steps:

- loaded tar
- ```sh
  tar -zxvf cutdown.tar.gz
  cd orchid-pgsql-cutdown/
  npm i
  ```
- changed username, password, host in .env to my local postgres
- created dbs manually:
  ```sql
  CREATE DATABASE identity; CREATE DATABASE identity_test;
  ```
- npm run migrate

And I have no errors.

I think I know the reason:

> The other thing to add is that the logs show 2 entries Created versions table

It is correct, 2 logs because there are two databases - 2nd for tests.

These logs indicate that it was successful.

> error: duplicate key value violates unique constraint "pg_type_typname_nsp_index"

This happened right after this index:
```sql
CREATE UNIQUE INDEX "hid_to_email_email_idx" ON "hid_to_email" ("email")
```

I assumed that this happened because the index name was already taken. I tried to reproduce that, and it failed with a similar error, but the error is much more readable, it is obvious:

![image](https://github.com/romeerez/orchid-orm/assets/42248135/7b1a7ed8-6ced-4913-a7ac-8b7bb7977adc)

Wondering, is it also colored on your side? If yes, we can see the exact SQL that failed by the color.

I'm using Postgres 16, not so long ago I was using Postgres 15 and all was fine. It's possible that due to an old version your error logs are less human-friendly.

**Comment by krichards** [comment] 2023-11-27 11:38
If you check the first error I posted it shows that it is schemaMigrations that is causing the error.

![migrations-error](https://github.com/romeerez/orchid-orm/assets/635632/0eab6f19-b201-4edb-905b-842871daf580)

`
 try {
    await db.query(
      `CREATE TABLE ${quoteWithSchema({
        name: config.migrationsTable
      })} ( version TEXT NOT NULL )`
    );
    (_b = config.logger) == null ? void 0 : _b.log("Created versions table");
  } catch (err) {
    console.log('XXXXXXXX   ' + err.code)
    if (err.code === "42P07") {
      (_c = config.logger) == null ? void 0 : _c.log("Versions table exists");
    } else {
      throw err;
    }
  }
`

This is failing - but the code seems to be relying on a specific error code to ignore if it already exists.  I am getting a different error code 23505.  Perhaps the error code returned has a race condition??

**Comment by krichards** [comment] 2023-11-27 11:42
Found a related issue

https://stackoverflow.com/questions/74261789/postgres-create-table-if-not-exists-%E2%87%92-23505

**Comment by romeerez** [comment] 2024-02-21 01:45
So it was solved back then, should be fine to close this.

**Closed by romeerez** 2024-02-21 01:45 UTC
