### ISSUE TITLE
Query promise result lost on `then`

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#88] opened 2023-05-24 03:31 UTC
### Problem

Long story short,

```ts
await db.user // [ { id: 1 }, { id: 2 } ]
await db.user.then((x) => x) // undefined
```

### Expected

The two lines above return the same result.

**Comment by romeerez** [comment] 2023-05-24 03:43
Can't reproduce:

```ts
const user = await db.user.then((x) => x);
// okay
user[0];
// ts error: name doesn't exist on type Pick<...>[]
user.name;
```

**Comment by IlyaSemenov** [comment] 2023-05-24 03:51
Complete reproduction:

```ts
import { createBaseTable, orchidORM } from "orchid-orm"

const BaseTable = createBaseTable()

class UserTable extends BaseTable {
  readonly table = "user"
  columns = this.setColumns((t) => ({
    id: t.identity().primaryKey(),
  }))
}

const db = orchidORM(
  {
    databaseURL: process.env.DATABASE_URL,
  },
  {
    user: UserTable,
  }
)

await db.$adapter.query(`
  drop table if exists "user";
  create table "user" (
    id serial primary key
  );
`)

await db.user.create({})
console.log(await db.user)
console.log(await db.user.then((x) => x))

await db.$close()
```

```
~/gh/orchid-graphql orchid*
❯ p vite-node playground/test.ts
[ { id: 1 } ]
undefined
```

Deps:
- orchid-orm 1.9.31
- pqb 0.11.24

**Comment by romeerez** [comment] 2023-05-25 06:47
Published a fix for this, also fixed the `catch` method.

**Closed by romeerez** 2023-05-25 06:47 UTC
Labels: bug
