### ISSUE TITLE
Selecting a nested subquery causes 'Record is not found' to be thrown

### ISSUE THREAD

**Issue by lithdew** [romeerez/orchid-orm#45] opened 2023-03-23 05:03 UTC
```ts
export function accounts() {
  return db.accounts.select("id", "publicKey", "name", "alias", "bio", "createdAt", "updatedAt", "lastSeenAt", "isVerified")
    .select({
      numPosts: q => db.posts.count().whereNotExists(db.commentsOnPosts, { commentId: "id" }).where(q.raw("posts.author_id = accounts.id")),
      numComments: q => db.posts.count().whereExists(db.commentsOnPosts, { commentId: "id" }).where(q.raw("posts.author_id = accounts.id")),
    });
}

const result = await db.posts.select({
  author: q => db.$from(accounts()).as("accounts_view").where(q.raw("accounts_view.id = posts.author_id")).take(),
});
```

```console
    Record is not found

      at parseResult (../../node_modules/pqb/src/queryMethods/then.ts:238:38)
      at Object.numPosts (../../node_modules/pqb/src/queryMethods/select.ts:148:18)
      at parseRecord (../../node_modules/pqb/src/queryMethods/then.ts:257:31)
      at ../../node_modules/pqb/src/queryMethods/then.ts:191:36
          at Array.map (<anonymous>)
      at parseResult (../../node_modules/pqb/src/queryMethods/then.ts:191:23)
      at Object.author (../../node_modules/pqb/src/queryMethods/select.ts:148:18)
      at parseRecord (../../node_modules/pqb/src/queryMethods/then.ts:257:31)
      at ../../node_modules/pqb/src/queryMethods/then.ts:191:36
          at Array.map (<anonymous>)
      at parseResult (../../node_modules/pqb/src/queryMethods/then.ts:191:23)
      at Object.handleResult (../../node_modules/pqb/src/queryMethods/then.ts:51:10)
      at then (../../node_modules/pqb/src/queryMethods/then.ts:123:34)
```

**Comment by lithdew** [comment] 2023-03-23 05:08
The query produced for `result` after suffixing `.log(true)` however is correct.

```sql
SELECT (SELECT COALESCE(json_agg(row_to_json("t".*)), '[]') FROM (SELECT * FROM (SELECT "accounts"."id", "accounts"."public_key" AS "publicKey", "accounts"."name", "accounts"."alias", "accounts"."bio", "accounts"."created_at" AS "createdAt", "accounts"."updated_at" AS "updatedAt", "accounts"."last_seen_at" AS "lastSeenAt", "accounts"."is_verified" AS "isVerified", (SELECT count(*) FROM "posts" WHERE NOT EXISTS (SELECT 1 FROM "comments_on_posts" WHERE "comments_on_posts"."comment_id" = "posts"."id" LIMIT 1) AND (posts.author_id = accounts.id)) AS "numPosts", (SELECT count(*) FROM "posts" WHERE EXISTS (SELECT 1 FROM "comments_on_posts" WHERE "comments_on_posts"."comment_id" = "posts"."id" LIMIT 1) AND (posts.author_id = accounts.id)) AS "numComments" FROM "accounts") AS "accounts_view" WHERE "accounts_view"."id" = posts.author_id) AS "t") AS "author" FROM "posts"
```

**Comment by lithdew** [comment] 2023-03-23 05:09
The query produced by suffixing `.log(true)` to `result`:
```sql
SELECT (SELECT COALESCE(json_agg(row_to_json("t".*)), '[]') FROM (SELECT * FROM (SELECT "accounts"."id", "accounts"."public_key" AS "publicKey", "accounts"."name", "accounts"."alias", "accounts"."bio", "accounts"."created_at" AS "createdAt", "accounts"."updated_at" AS "updatedAt", "accounts"."last_seen_at" AS "lastSeenAt", "accounts"."is_verified" AS "isVerified", (SELECT count(*) FROM "posts" WHERE NOT EXISTS (SELECT 1 FROM "comments_on_posts" WHERE "comments_on_posts"."comment_id" = "posts"."id" LIMIT 1) AND (posts.author_id = accounts.id)) AS "numPosts", (SELECT count(*) FROM "posts" WHERE EXISTS (SELECT 1 FROM "comments_on_posts" WHERE "comments_on_posts"."comment_id" = "posts"."id" LIMIT 1) AND (posts.author_id = accounts.id)) AS "numComments" FROM "accounts") AS "accounts_view" WHERE "accounts_view"."id" = posts.author_id) AS "t") AS "author" FROM "posts"
```

**Comment by romeerez** [comment] 2023-03-24 00:35
I guess it's not a bug, maybe it's not very intuitive, but it makes sense.

The query builder has a method `take` which you have used for `author` sub-query, and this method ensures that the record was loaded, and will throw an error in case no record is found.

Here is my simplified example, the resulting type has a non-optional `two`, and query-builder must ensure that the actual result fully matches expectations:

```ts
type Result = Array<{ two: Two }>

const result: Result = db.one.select({
  two: () => db.two.take()
})
```

And if you expect sub query to not have results and it's okay for the use case, use `takeOptional()` instead:

```ts
type Result = Array<{ two?: Two }> // note the `?`

const result: Result = db.one.select({
  two: () => db.two.takeOptional()
})
```

So if this is the case it's not a bug and we can close it, but if you run the SQL and all records have `author` than it would be a bug.

**Comment by lithdew** [comment] 2023-03-24 07:55
I tried to use `takeOptional()` as well and it seems to throw the same error:

```ts
const result = await db.posts.select({
  author: q => db.$from(accounts()).as("accounts_view").where({ id: q.raw("posts.author_id") }).takeOptional(),
}).log(true);
console.log(result);
```

```console
  ● Orchid ORM › should work

    Record is not found

      at parseResult (../../node_modules/pqb/src/queryMethods/then.ts:238:38)
      at Object.numPosts (../../node_modules/pqb/src/queryMethods/select.ts:148:18)
      at parseRecord (../../node_modules/pqb/src/queryMethods/then.ts:257:31)
      at parseResult (../../node_modules/pqb/src/queryMethods/then.ts:199:24)
      at Object.author (../../node_modules/pqb/src/queryMethods/select.ts:148:18)
      at parseRecord (../../node_modules/pqb/src/queryMethods/then.ts:257:31)
      at ../../node_modules/pqb/src/queryMethods/then.ts:191:36
          at Array.map (<anonymous>)
      at parseResult (../../node_modules/pqb/src/queryMethods/then.ts:191:23)
      at Object.handleResult (../../node_modules/pqb/src/queryMethods/then.ts:51:10)
      at then (../../node_modules/pqb/src/queryMethods/then.ts:123:34)
```

I double-checked in the database on how many entries may not have `author`:

```console
# select count(*) from posts where not exists(select * from accounts where accounts.id = posts.author_id);
 count 
-------
     0
(1 row)
```

**Comment by romeerez** [comment] 2023-03-24 08:19
Thanks for finding it, I'll fix

**Comment by romeerez** [comment] 2023-03-25 03:25
Published a fix for this.

By the way, there is a shorter form for `where().take()` - `findBy`:

```ts
// throw if not found
.findBy({ id: q.raw("posts.author_id") }),

// undefined if not found
.findByOptional({ id: q.raw("posts.author_id") }),
```

**Closed** 2023-03-25 03:25 UTC
