### ISSUE TITLE
querySchema, updateSchema: Cannot read properties of undefined (reading 'optional')

### ISSUE THREAD

**Issue by minkoonim** [romeerez/orchid-orm#335] opened 2024-07-17 09:57 UTC
I update orchid everytime I open the project,
I think few days ago this didn't occur,
but today it happened. 

```
Cannot read properties of undefined (reading 'optional')
```

```
  at node_modules/zod/lib/index.mjs:2626:45
  at Array.forEach (<anonymous>)
  at ZodObject.partial (node_modules/zod/lib/index.mjs:2620:37)
  at Function.updateSchema (node_modules/orchid-orm-schema-to-zod/src/zod.ts:880:7)
  at Function.updateSchema (node_modules/orchid-orm/src/baseTable.ts:541:59)
```

I went to check what is happening,
please check comment inside zod "partial" script

```
// table definition
export class UserTable extends BaseTable {
  readonly table = 'user'

  columns = this.setColumns(t => ({
    id: t.id,
    email: t.string().email().unique(),
    password: t.string().min(8).max(24),
    firstName: t.string(),
    lastName: t.string(),
    active: t.active,
  }))

  relations = {
    staff: this.hasOne(() => StaffTable, {
      columns: ['id'],
      references: ['userId'],
    }),
  }
}

// zod part from node_modules/zod/lib/index.mjs:2633:45
partial(mask) {
    const newShape = {};
    console.log({shape: this.shape})
    // all the columns are there,
    // but "relations" are all undefined

    util.objectKeys(this.shape).forEach((key) => {
        const fieldSchema = this.shape[key];
        if (mask && !mask[key]) {
            newShape[key] = fieldSchema;
        }
        else {
            console.log({fieldSchema: fieldSchema === undefined ? 'undefined': 'not undefined', key})
            // { fieldSchema: 'not undefined', key: 'email' }
            // { fieldSchema: 'not undefined', key: 'password' }
            // { fieldSchema: 'not undefined', key: 'firstName' }
            // { fieldSchema: 'not undefined', key: 'lastName' }
            // { fieldSchema: 'not undefined', key: 'active' }
            // { fieldSchema: 'undefined', key: 'staff' }  ---> this is from relation!
            newShape[key] = fieldSchema.optional();
        }
    });
    return new ZodObject({
        ...this._def,
        shape: () => newShape,
    });
}

```

**Comment by romeerez** [comment] 2024-07-17 20:19
Looks like relation fields are accidentally added to zod schemas, and if so it is a bug in ORM and should be fixed.

**Comment by minkoonim** [comment] 2024-07-20 07:58
thanks

**Comment by minkoonim** [comment] 2024-07-28 05:36
from orchid-orm-schema-to-zod
querySchema's looping through columns include **relations**,
resulting in 
```
Cannot read properties of undefined (reading 'optional')
```

```
  querySchema() {
    const shape = {};
    const { shape: columns } = this.prototype.columns;
    for (const key in columns) {
      shape[key] = columns[key].querySchema.optional();
    }
    return z.object(shape);
  },
  createSchema() {
    const input = this.inputSchema();
    const shape = {};
    const { shape: columns } = this.prototype.columns;
    for (const key in columns) {
      const column = columns[key];
      if (!column.data.primaryKey) {
        shape[key] = input.shape[key];
        if (column.data.isNullable || column.data.default !== void 0) {
          shape[key] = shape[key].optional();
        }
      }
    }
    return z.object(shape);
  },
```

**Comment by romeerez** [comment] 2024-07-28 12:53
What are your tables look like?

I tried all kinds of relations and the `querySchema` works on my machine, so I cannot reproduce this.

**Comment by romeerez** [comment] 2024-07-28 13:16
I published a fix, should be fine now.

**Closed by romeerez** 2024-07-28 13:16 UTC
