### ISSUE TITLE
Connections as nested arrays

### ISSUE THREAD

**Issue by quinnvaughn** [romeerez/orchid-orm#26] opened 2023-02-22 01:50 UTC
Possibly dumb question, but why am I getting connections like books in this example:

```
const authorWithBooks: AuthorResult = await db.author.select(
  'id',
  'name',
  {
    books: (q) => q.books
      .select('id', 'title')
      .where(...conditions)
      .order('title')
      .limit(5),
  }
).take()
```

being returned as a nested array? I've tried it several different ways and they all end up returning `books: [Array[]]`, which is obviously not what I'm looking for, I'm looking for `books: Array[]`. I then would have to go in and flatten books, which is inconvenient, and the documentation makes no mention of this, and even implies it should return as the latter. 

If trying to do it this way (which btw this documentation is also wrong)
```
// if the `required` option is not set in the table class,
// type of author will be Author | null 
const booksWithAuthor: Book & { author: Author } = await db.book
  .select('*', 'author')
  .take();

const authorWithBooks: Author & { books: Book[] } = await db.book
  .select('*', 'author')
  .take();
```

I get the same thing, so I'm wondering why this is happening?

**Comment by romeerez** [comment] 2023-02-22 03:30
Sorry, that's a very embarrassing bug, I'll figure out something to make tests more reliable. Will fix.

**Comment by romeerez** [comment] 2023-02-22 04:58
Fixed now! Please update `orchid-orm` and `pqb` to the latest versions to get the fix.

**Comment by romeerez** [comment] 2023-02-22 06:33
Fixed now! Please update `orchid-orm`,  `pqb`, and all related libs to the latest versions to get the fix.

**Comment by romeerez** [comment] 2023-02-22 06:43
The fix is for returning records from a sub query, it is a flat array now as intended.

But `.select('*')` doesn't work due to TS type, I'll fix this later.

```ts
db.book.select('*') // TS error
```

Meanwhile, you can use `selectAll` instead:

```ts
db.book.selectAll().select('author')
```

**Comment by romeerez** [comment] 2023-03-19 09:28
Now selecting `*` is supported and the following should work fine:

```ts
const booksWithAuthor: Book & { author: Author } = await db.book
  .select('*', 'author')
  .take();

const authorWithBooks: Author & { books: Book[] } = await db.author
  .select('*', 'books')
  .take();
```

**Closed by romeerez** 2023-03-19 09:28 UTC
Labels: bug
